name: Build and Deploy to Cloud Run

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    RUN_REGION: ${{ secrets.REGION }}
    SERVICE_NAME: ${{ secrets.SERVICE_NAME }}

jobs:
    setup-build-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # Setup gcloud CLI
            - uses: google-github-actions/setup-gcloud@v1
              with:
                  version: '>= 363.0.0'
                  service_account_email: ${{ secrets.SA_EMAIL }}
                  service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}

            # Configure gcloud CLI
            - name: gcloud Set up
              run: |
                  gcloud config set project $PROJECT_ID
            # Build and push image to Google Container Registry
            - name: Build
              run: |
                  gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
            # Deploy image to Cloud Run
            - name: Deploy
              run: |
                  gcloud run deploy $SERVICE_NAME \
                    --region $RUN_REGION \
                    --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
                    --platform managed
